packages:
  - playgrounds/*

allowBuilds:
  "@jaminzhou/codex-app-server-client@https://codeload.github.com/JaminZhou/codex-app-server-client/tar.gz/97ffcd496aa0aefdbdc868d13a5bce4e09a5afc5": true
  electron: true
  esbuild: true
