import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  currentThreadVisualAssetIds,
  serializeCurrentThreadVisualAssetSubset,
} from "../scripts/current-thread-visual-assets.mjs";

const manifest = JSON.parse(
  readFileSync(
    new URL("../research/visual-assets.json", import.meta.url),
    "utf8",
  ),
);
const trackedSubset = readFileSync(
  new URL("../demo/current-thread-visual-assets.json", import.meta.url),
  "utf8",
);

describe("current-thread visual asset subset", () => {
  it("is generated byte-for-byte from the current manifest", () => {
    expect(serializeCurrentThreadVisualAssetSubset(manifest)).toBe(
      trackedSubset,
    );
  });

  it("includes every promoted MCP replay asset", () => {
    expect(currentThreadVisualAssetIds).toEqual(
      expect.arrayContaining([
        "sidebar-explore",
        "thread-mcp-tool",
        "thread-activity-chevron",
        "thread-header-share",
        "thread-reconnecting",
      ]),
    );
    expect(currentThreadVisualAssetIds).toHaveLength(45);
  });
});
