import type { KeyboardShortcutEntry } from "codex-ui-kit";

/** Current 26.825.51511 visible Keyboard shortcuts route fixture. */
export const currentKeyboardShortcuts = [
  {
    id: "new-chat-start-a-new-chat",
    name: "New chat",
    description: "Start a new chat",
    shortcuts: ["⌘N","⇧⌘O"],
  },
  {
    id: "new-temporary-chat-start-a-chat-that-won-t-appear-in-history",
    name: "New Temporary Chat",
    description: "Start a chat that won't appear in history",
    shortcuts: ["⇧⌘N"],
  },
  {
    id: "quick-chat-start-a-lightweight-chat-in-the-quick-composer",
    name: "Quick chat",
    description: "Start a lightweight chat in the quick composer",
    shortcuts: ["⌥⌘N"],
  },
  {
    id: "archive-chat-archive-the-current-chat",
    name: "Archive chat",
    description: "Archive the current chat",
    shortcuts: ["⇧⌘A"],
  },
  {
    id: "new-standalone-chat-start-a-new-chat-outside-of-any-project",
    name: "New standalone chat",
    description: "Start a new chat outside of any project",
    shortcuts: ["⌥⌘O"],
  },
  {
    id: "open-side-chat-open-the-current-chat-in-a-side-chat",
    name: "Open side chat",
    description: "Open the current chat in a side chat",
    shortcuts: ["⌥⌘S"],
  },
  {
    id: "mark-as-unread-mark-the-current-chat-as-unread",
    name: "Mark as unread",
    description: "Mark the current chat as unread",
    shortcuts: ["⇧⌘U"],
  },
  {
    id: "open-in-new-window-open-the-current-chat-in-a-new-window",
    name: "Open in new window",
    description: "Open the current chat in a new window",
    shortcuts: [],
  },
  {
    id: "toggle-pin-pin-or-unpin-the-current-chat",
    name: "Toggle pin",
    description: "Pin or unpin the current chat",
    shortcuts: ["⌥⌘P"],
  },
  {
    id: "focus-browser-address-bar-focus-the-in-app-browser-address-bar",
    name: "Focus browser address bar",
    description: "Focus the in-app browser address bar",
    shortcuts: ["⌘L"],
  },
  {
    id: "focus-main-chat-move-keyboard-focus-to-the-main-chat-composer",
    name: "Focus main chat",
    description: "Move keyboard focus to the main chat composer",
    shortcuts: [],
  },
  {
    id: "focus-side-chat-move-keyboard-focus-to-an-open-side-chat-composer",
    name: "Focus side chat",
    description: "Move keyboard focus to an open side chat composer",
    shortcuts: [],
  },
  {
    id: "go-to-line-go-to-a-line-in-the-current-file",
    name: "Go to line",
    description: "Go to a line in the current file",
    shortcuts: ["⌘L"],
  },
  {
    id: "back-go-back-in-navigation-history",
    name: "Back",
    description: "Go back in navigation history",
    shortcuts: ["⌘[","Mouse Back"],
  },
  {
    id: "forward-go-forward-in-navigation-history",
    name: "Forward",
    description: "Go forward in navigation history",
    shortcuts: ["⌘]","Mouse Forward"],
  },
  {
    id: "next-recently-viewed-chat-cycle-to-the-next-recently-viewed-chat",
    name: "Next recently viewed chat",
    description: "Cycle to the next recently viewed chat",
    shortcuts: ["⌃Tab"],
  },
  {
    id: "next-tab-switch-to-the-next-tab",
    name: "Next tab",
    description: "Switch to the next tab",
    shortcuts: ["⌃Tab","⇧⌘]","⌥⌘Right"],
  },
  {
    id: "next-chat-switch-to-the-next-chat",
    name: "Next chat",
    description: "Switch to the next chat",
    shortcuts: ["⇧⌘]","⌥⌘Right"],
  },
  {
    id: "next-chat-needing-attention-switch-to-the-next-chat-awaiting-input-or-with-unread-activity",
    name: "Next chat needing attention",
    description: "Switch to the next chat awaiting input or with unread activity",
    shortcuts: ["⌥⌘A"],
  },
  {
    id: "previous-recently-viewed-chat-cycle-to-the-previous-recently-viewed-chat",
    name: "Previous recently viewed chat",
    description: "Cycle to the previous recently viewed chat",
    shortcuts: ["⌃⇧Tab"],
  },
  {
    id: "previous-tab-switch-to-the-previous-tab",
    name: "Previous tab",
    description: "Switch to the previous tab",
    shortcuts: ["⌃⇧Tab","⇧⌘[","⌥⌘Left"],
  },
  {
    id: "previous-chat-switch-to-the-previous-chat",
    name: "Previous chat",
    description: "Switch to the previous chat",
    shortcuts: ["⇧⌘[","⌥⌘Left"],
  },
  {
    id: "go-to-recent-chat-1-open-the-recently-updated-chat-in-this-shortcut-slot",
    name: "Go to recent chat 1",
    description: "Open the recently updated chat in this shortcut slot",
    shortcuts: ["⌥⌘1"],
  },
  {
    id: "go-to-recent-chat-2-open-the-recently-updated-chat-in-this-shortcut-slot",
    name: "Go to recent chat 2",
    description: "Open the recently updated chat in this shortcut slot",
    shortcuts: ["⌥⌘2"],
  },
  {
    id: "go-to-recent-chat-3-open-the-recently-updated-chat-in-this-shortcut-slot",
    name: "Go to recent chat 3",
    description: "Open the recently updated chat in this shortcut slot",
    shortcuts: ["⌥⌘3"],
  },
  {
    id: "go-to-recent-chat-4-open-the-recently-updated-chat-in-this-shortcut-slot",
    name: "Go to recent chat 4",
    description: "Open the recently updated chat in this shortcut slot",
    shortcuts: ["⌥⌘4"],
  },
  {
    id: "go-to-recent-chat-5-open-the-recently-updated-chat-in-this-shortcut-slot",
    name: "Go to recent chat 5",
    description: "Open the recently updated chat in this shortcut slot",
    shortcuts: ["⌥⌘5"],
  },
  {
    id: "go-to-recent-chat-6-open-the-recently-updated-chat-in-this-shortcut-slot",
    name: "Go to recent chat 6",
    description: "Open the recently updated chat in this shortcut slot",
    shortcuts: ["⌥⌘6"],
  },
  {
    id: "switch-chat-search-and-switch-to-a-chat",
    name: "Switch chat…",
    description: "Search and switch to a chat",
    shortcuts: [],
  },
  {
    id: "switch-to-chat-switch-to-chat",
    name: "Switch to Chat",
    description: "Switch to Chat",
    shortcuts: ["⌃1"],
  },
  {
    id: "switch-to-work-switch-to-work",
    name: "Switch to Work",
    description: "Switch to Work",
    shortcuts: ["⌃2"],
  },
  {
    id: "switch-to-codex-switch-to-codex",
    name: "Switch to Codex",
    description: "Switch to Codex",
    shortcuts: ["⌃3"],
  },
  {
    id: "toggle-activity-view-turn-the-sidebar-activity-view-on-or-off",
    name: "Toggle activity view",
    description: "Turn the sidebar activity view on or off",
    shortcuts: ["⌥⌘U"],
  },
  {
    id: "open-browser-tab-open-a-new-browser-tab",
    name: "Open browser tab",
    description: "Open a new browser tab",
    shortcuts: ["⌘T"],
  },
  {
    id: "open-review-tab-open-the-review-tab",
    name: "Open review tab",
    description: "Open the review tab",
    shortcuts: ["⌃⇧G"],
  },
  {
    id: "reopen-closed-tab-reopen-the-most-recently-closed-tab",
    name: "Reopen closed tab",
    description: "Reopen the most recently closed tab",
    shortcuts: ["⇧⌘T"],
  },
  {
    id: "toggle-bottom-panel-show-or-hide-the-bottom-panel",
    name: "Toggle bottom panel",
    description: "Show or hide the bottom panel",
    shortcuts: ["⌘J"],
  },
  {
    id: "toggle-browser-panel-show-or-hide-the-browser-panel",
    name: "Toggle browser panel",
    description: "Show or hide the browser panel",
    shortcuts: ["⇧⌘B"],
  },
  {
    id: "toggle-pinned-summary-show-or-hide-the-pinned-summary",
    name: "Toggle pinned summary",
    description: "Show or hide the pinned summary",
    shortcuts: [],
  },
  {
    id: "toggle-review-show-or-hide-review-for-the-current-git-backed-chat",
    name: "Toggle review",
    description: "Show or hide Review for the current Git-backed chat",
    shortcuts: [],
  },
  {
    id: "toggle-sidebar-show-or-hide-the-sidebar",
    name: "Toggle sidebar",
    description: "Show or hide the sidebar",
    shortcuts: ["⌘B"],
  },
  {
    id: "toggle-review-panel-show-or-hide-review-for-the-current-chat",
    name: "Toggle Review panel",
    description: "Show or hide Review for the current chat",
    shortcuts: ["⌥⌘B"],
  },
  {
    id: "open-terminal-open-the-terminal-panel",
    name: "Open terminal",
    description: "Open the terminal panel",
    shortcuts: ["⌃`"],
  },
  {
    id: "environment-action-1-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 1",
    description: "Run the environment action in this shortcut slot",
    shortcuts: ["⇧⌘D"],
  },
  {
    id: "environment-action-2-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 2",
    description: "Run the environment action in this shortcut slot",
    shortcuts: [],
  },
  {
    id: "environment-action-3-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 3",
    description: "Run the environment action in this shortcut slot",
    shortcuts: [],
  },
  {
    id: "environment-action-4-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 4",
    description: "Run the environment action in this shortcut slot",
    shortcuts: [],
  },
  {
    id: "environment-action-5-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 5",
    description: "Run the environment action in this shortcut slot",
    shortcuts: [],
  },
  {
    id: "environment-action-6-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 6",
    description: "Run the environment action in this shortcut slot",
    shortcuts: [],
  },
  {
    id: "environment-action-7-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 7",
    description: "Run the environment action in this shortcut slot",
    shortcuts: [],
  },
  {
    id: "environment-action-8-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 8",
    description: "Run the environment action in this shortcut slot",
    shortcuts: [],
  },
  {
    id: "environment-action-9-run-the-environment-action-in-this-shortcut-slot",
    name: "Environment action 9",
    description: "Run the environment action in this shortcut slot",
    shortcuts: [],
  },
  {
    id: "commit-or-push-open-commit-or-push-options",
    name: "Commit or push",
    description: "Open commit or push options",
    shortcuts: [],
  },
  {
    id: "create-branch-open-branch-creation-options",
    name: "Create branch",
    description: "Open branch creation options",
    shortcuts: [],
  },
  {
    id: "create-draft-pr-open-draft-pull-request-creation-options",
    name: "Create draft PR",
    description: "Open draft pull request creation options",
    shortcuts: [],
  },
  {
    id: "create-pr-open-pull-request-creation-options",
    name: "Create PR",
    description: "Open pull request creation options",
    shortcuts: [],
  },
  {
    id: "merge-pr-open-pull-request-merge-options",
    name: "Merge PR",
    description: "Open pull request merge options",
    shortcuts: [],
  },
  {
    id: "open-pr-on-github-open-the-pull-request-linked-to-the-current-chat",
    name: "Open PR on GitHub",
    description: "Open the pull request linked to the current chat",
    shortcuts: [],
  },
  {
    id: "open-folder-add-a-local-project-to-chatgpt",
    name: "Open folder",
    description: "Add a local project to ChatGPT",
    shortcuts: ["⌘O"],
  },
  {
    id: "force-reload-skills-refresh-the-skill-catalog-for-the-current-context",
    name: "Force reload skills",
    description: "Refresh the skill catalog for the current context",
    shortcuts: [],
  },
  {
    id: "go-to-skills-browse-installed-and-recommended-skills",
    name: "Go to skills",
    description: "Browse installed and recommended skills",
    shortcuts: [],
  },
  {
    id: "import-from-other-ai-apps-import-from-other-ai-apps",
    name: "Import from other AI apps",
    description: "Import from other AI apps",
    shortcuts: [],
  },
  {
    id: "keyboard-shortcuts-customize-keyboard-shortcuts",
    name: "Keyboard shortcuts",
    description: "Customize keyboard shortcuts",
    shortcuts: [],
  },
  {
    id: "mcp-configure-mcp-servers",
    name: "MCP",
    description: "Configure MCP servers",
    shortcuts: [],
  },
  {
    id: "personality-adjust-tone-and-response-style",
    name: "Personality",
    description: "Adjust tone and response style",
    shortcuts: [],
  },
  {
    id: "clear-all-unreads-mark-all-chats-and-scheduled-task-updates-as-read",
    name: "Clear all unreads",
    description: "Mark all chats and scheduled task updates as read",
    shortcuts: ["⇧Esc"],
  },
  {
    id: "feedback-send-product-feedback-to-the-chatgpt-team",
    name: "Feedback",
    description: "Send product feedback to the ChatGPT team",
    shortcuts: [],
  },
  {
    id: "log-out-sign-out-of-chatgpt",
    name: "Log out",
    description: "Sign out of ChatGPT",
    shortcuts: [],
  },
  {
    id: "manage-scheduled-tasks-create-or-manage-scheduled-tasks-from-the-current-page",
    name: "Manage scheduled tasks",
    description: "Create or manage scheduled tasks from the current page",
    shortcuts: [],
  },
  {
    id: "show-pet-open-the-pet-overlay",
    name: "Show pet",
    description: "Open the pet overlay",
    shortcuts: [],
  },
  {
    id: "open-control-window-open-the-voice-chat-control-window",
    name: "Open control window",
    description: "Open the voice chat control window",
    shortcuts: [],
  },
  {
    id: "redo-last-action-redo-the-most-recently-undone-app-action",
    name: "Redo last action",
    description: "Redo the most recently undone app action",
    shortcuts: ["⇧⌘Z"],
  },
  {
    id: "settings-open-chatgpt-settings",
    name: "Settings",
    description: "Open ChatGPT settings",
    shortcuts: ["⌘,"],
  },
  {
    id: "undo-last-action-undo-the-most-recent-app-action",
    name: "Undo last action",
    description: "Undo the most recent app action",
    shortcuts: ["⌘Z"],
  },
  {
    id: "approve-request-approve-the-active-request",
    name: "Approve request",
    description: "Approve the active request",
    shortcuts: ["⏎"],
  },
  {
    id: "decline-request-decline-the-active-request",
    name: "Decline request",
    description: "Decline the active request",
    shortcuts: ["Esc"],
  },
  {
    id: "close-tab-close-the-active-tab",
    name: "Close Tab",
    description: "Close the active tab",
    shortcuts: ["⌘W"],
  },
  {
    id: "close-close-the-active-window",
    name: "Close",
    description: "Close the active window",
    shortcuts: ["⌘W"],
  },
  {
    id: "attach-files-and-folders-attach-files-and-folders-to-the-active-composer",
    name: "Attach files and folders",
    description: "Attach files and folders to the active composer",
    shortcuts: [],
  },
  {
    id: "add-photos-add-photos-to-the-active-composer",
    name: "Add photos",
    description: "Add photos to the active composer",
    shortcuts: [],
  },
  {
    id: "clear-prompt-clear-the-current-composer-prompt",
    name: "Clear prompt",
    description: "Clear the current composer prompt",
    shortcuts: [],
  },
  {
    id: "cycle-reasoning-effort-cycle-through-composer-reasoning-effort-options",
    name: "Cycle reasoning effort",
    description: "Cycle through composer reasoning effort options",
    shortcuts: [],
  },
  {
    id: "decrease-reasoning-effort-decrease-the-current-composer-reasoning-effort",
    name: "Decrease reasoning effort",
    description: "Decrease the current composer reasoning effort",
    shortcuts: [],
  },
  {
    id: "increase-reasoning-effort-increase-the-current-composer-reasoning-effort",
    name: "Increase reasoning effort",
    description: "Increase the current composer reasoning effort",
    shortcuts: [],
  },
  {
    id: "open-model-picker-open-the-composer-model-picker",
    name: "Open model picker",
    description: "Open the composer model picker",
    shortcuts: ["⌃⇧M"],
  },
  {
    id: "open-project-picker-open-the-composer-project-picker",
    name: "Open project picker",
    description: "Open the composer project picker",
    shortcuts: ["⌥⇧⌘O"],
  },
  {
    id: "queue-prompt-submit-the-current-composer-prompt-as-a-queued-message",
    name: "Queue prompt",
    description: "Submit the current composer prompt as a queued message",
    shortcuts: [],
  },
  {
    id: "start-dictation-start-dictation-in-the-current-composer",
    name: "Start dictation",
    description: "Start dictation in the current composer",
    shortcuts: ["⌃⇧D"],
  },
  {
    id: "toggle-voice-chat-start-or-stop-voice-chat",
    name: "Toggle voice chat",
    description: "Start or stop voice chat",
    shortcuts: ["⌃⇧V"],
  },
  {
    id: "steer-prompt-submit-the-current-composer-prompt-as-a-steering-message",
    name: "Steer prompt",
    description: "Submit the current composer prompt as a steering message",
    shortcuts: [],
  },
  {
    id: "send-message-send-the-current-composer-message",
    name: "Send message",
    description: "Send the current composer message",
    shortcuts: [],
  },
  {
    id: "send-message-in-background-send-the-current-composer-message-without-opening-its-chat",
    name: "Send message in background",
    description: "Send the current composer message without opening its chat",
    shortcuts: ["⌘⏎"],
  },
  {
    id: "toggle-fast-mode-turn-fast-mode-on-or-off-in-the-current-composer",
    name: "Toggle Fast mode",
    description: "Turn Fast mode on or off in the current composer",
    shortcuts: [],
  },
  {
    id: "toggle-plan-mode-turn-plan-mode-on-or-off-in-the-current-composer",
    name: "Toggle plan mode",
    description: "Turn plan mode on or off in the current composer",
    shortcuts: [],
  },
  {
    id: "toggle-cloud-local-switch-chatgpt-work-between-cloud-and-local-execution",
    name: "Toggle Cloud/Local",
    description: "Switch ChatGPT Work between cloud and local execution",
    shortcuts: [],
  },
  {
    id: "toggle-local-worktree-switch-the-current-composer-between-local-and-a-new-worktree",
    name: "Toggle Local/Worktree",
    description: "Switch the current composer between local and a new worktree",
    shortcuts: [],
  },
  {
    id: "copy-as-markdown-copy-the-current-chat-as-markdown",
    name: "Copy as Markdown",
    description: "Copy the current chat as Markdown",
    shortcuts: [],
  },
  {
    id: "copy-conversation-path-copy-the-current-chat-path",
    name: "Copy conversation path",
    description: "Copy the current chat path",
    shortcuts: ["⌥⇧⌘C"],
  },
  {
    id: "copy-deeplink-copy-a-deeplink-to-the-current-chat",
    name: "Copy deeplink",
    description: "Copy a deeplink to the current chat",
    shortcuts: ["⌥⌘L"],
  },
  {
    id: "copy-working-directory-copy-the-current-chat-working-directory",
    name: "Copy working directory",
    description: "Copy the current chat working directory",
    shortcuts: ["⇧⌘C"],
  },
  {
    id: "fork-chat-fork-the-current-chat",
    name: "Fork chat",
    description: "Fork the current chat",
    shortcuts: [],
  },
  {
    id: "hold-to-dictate-hotkey-hold-anywhere-on-desktop-to-dictate-where-your-cursor-is",
    name: "Hold-to-dictate hotkey",
    description: "Hold anywhere on desktop to dictate where your cursor is",
    keywords: ["dictation"],
    shortcuts: [],
  },
  {
    id: "toggle-dictation-hotkey-press-once-anywhere-on-desktop-to-dictate-then-press-again-to-stop",
    name: "Toggle dictation hotkey",
    description: "Press once anywhere on desktop to dictate, then press again to stop",
    shortcuts: [],
  },
  {
    id: "force-reload-browser-page-force-reload-the-active-browser-page",
    name: "Force Reload Browser Page",
    description: "Force reload the active browser page",
    shortcuts: ["⇧⌘R"],
  },
  {
    id: "popout-window-hotkey-show-or-hide-popout-window-from-anywhere-on-desktop",
    name: "Popout Window hotkey",
    description: "Show or hide Popout Window from anywhere on desktop",
    shortcuts: [],
  },
  {
    id: "browser-back-go-back-in-browser-history",
    name: "Browser back",
    description: "Go back in browser history",
    shortcuts: ["⌘Left"],
  },
  {
    id: "browser-forward-go-forward-in-browser-history",
    name: "Browser forward",
    description: "Go forward in browser history",
    shortcuts: ["⌘Right"],
  },
  {
    id: "new-window-open-a-new-window",
    name: "New Window",
    description: "Open a new window",
    shortcuts: [],
  },
  {
    id: "open-command-menu-open-the-command-menu",
    name: "Open command menu",
    description: "Open the command menu",
    shortcuts: ["⌘K","⇧⌘P"],
  },
  {
    id: "voice-chat-hotkey-start-a-voice-chat-from-anywhere-on-desktop",
    name: "Voice Chat hotkey",
    description: "Start a Voice Chat from anywhere on desktop",
    shortcuts: [],
  },
  {
    id: "end-voice-chat-end-the-active-voice-chat",
    name: "End Voice Chat",
    description: "End the active Voice Chat",
    shortcuts: [],
  },
  {
    id: "toggle-voice-chat-microphone-mute-or-unmute-your-microphone-during-a-voice-chat",
    name: "Toggle Voice Chat microphone",
    description: "Mute or unmute your microphone during a Voice Chat",
    shortcuts: [],
  },
  {
    id: "toggle-voice-chat-audio-mute-or-unmute-voice-chat-audio",
    name: "Toggle Voice Chat audio",
    description: "Mute or unmute Voice Chat audio",
    shortcuts: [],
  },
  {
    id: "reload-browser-page-reload-the-active-browser-page",
    name: "Reload Browser Page",
    description: "Reload the active browser page",
    shortcuts: ["⌘R"],
  },
  {
    id: "rename-chat-rename-the-current-chat",
    name: "Rename chat",
    description: "Rename the current chat",
    shortcuts: ["⌥⌘R"],
  },
  {
    id: "search-files-search-files",
    name: "Search Files…",
    description: "Search files",
    shortcuts: ["⌘P"],
  },
  {
    id: "show-keyboard-shortcuts-show-the-shortcuts-available-right-now",
    name: "Show keyboard shortcuts",
    description: "Show the shortcuts available right now",
    shortcuts: ["⌘/"],
  },
  {
    id: "go-to-chat-1-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 1",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘1"],
  },
  {
    id: "go-to-chat-2-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 2",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘2"],
  },
  {
    id: "go-to-chat-3-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 3",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘3"],
  },
  {
    id: "go-to-chat-4-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 4",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘4"],
  },
  {
    id: "go-to-chat-5-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 5",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘5"],
  },
  {
    id: "go-to-chat-6-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 6",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘6"],
  },
  {
    id: "go-to-chat-7-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 7",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘7"],
  },
  {
    id: "go-to-chat-8-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 8",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘8"],
  },
  {
    id: "go-to-chat-9-open-the-visible-chat-in-this-shortcut-slot",
    name: "Go to chat 9",
    description: "Open the visible chat in this shortcut slot",
    shortcuts: ["⌘9"],
  },
  {
    id: "toggle-file-tree-toggle-the-file-tree-panel",
    name: "Toggle File Tree",
    description: "Toggle the file tree panel",
    shortcuts: ["⇧⌘E"],
  },
  {
    id: "toggle-maximize-side-panel-expand-or-restore-the-side-panel",
    name: "Toggle maximize side panel",
    description: "Expand or restore the side panel",
    shortcuts: [],
  },
  {
    id: "start-trace-recording-start-or-stop-trace-recording",
    name: "Start Trace Recording",
    description: "Start or stop trace recording",
    shortcuts: ["⇧⌘S"],
  },
] satisfies readonly KeyboardShortcutEntry[];
