import { expect, it } from "vitest";
import { mkdtemp, writeFile, readFile, rename, unlink, chmod } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { commitGitPreview, readGitCommitPreview } from "../electron/git-commit-preview";

it("previews the exact staged content without staging dirty or untracked files", async () => {
  const directory = await mkdtemp(join(tmpdir(), "ui-kit-commit-preview-"));
  const exec = promisify(execFile);
  const git = async (...args: string[]) => (await exec("git", args, { cwd: directory })).stdout.trim();
  await git("init", "-b", "main");
  await writeFile(join(directory, "file with spaces.txt"), "staged content\n");
  await git("add", "file with spaces.txt");
  await writeFile(join(directory, "file with spaces.txt"), "unstaged later content\n");
  await writeFile(join(directory, "untracked.txt"), "not reviewed\n");
  const before = await git("status", "--porcelain");
  const preview = await readGitCommitPreview(directory);
  expect(preview).toMatchObject({ branch: "main", head: null, stagedFiles: ["file with spaces.txt"], hasUnstagedChanges: true, hasUntrackedFiles: true });
  expect(preview.stagedPatch).toContain("+staged content");
  expect(preview.stagedPatch).not.toContain("unstaged later content");
  expect(preview.stagedPatch).not.toContain("not reviewed");
  expect((await readGitCommitPreview(directory)).fingerprint).toBe(preview.fingerprint);
  expect(await git("status", "--porcelain")).toBe(before);
  expect(await readFile(join(directory, "file with spaces.txt"), "utf8")).toBe("unstaged later content\n");
  await git("add", "file with spaces.txt");
  expect((await readGitCommitPreview(directory)).fingerprint).not.toBe(preview.fingerprint);
});

it("reads detached HEAD, binary additions, renames and deletions without changing the index", async () => {
  const directory = await mkdtemp(join(tmpdir(), "ui-kit-commit-preview-edges-"));
  const exec = promisify(execFile);
  const git = async (...args: string[]) => (await exec("git", args, { cwd: directory })).stdout.trim();
  await git("init", "-b", "main");
  await git("config", "user.name", "Preview Test");
  await git("config", "user.email", "preview@example.invalid");
  await writeFile(join(directory, "original.txt"), "unchanged rename content\n");
  await writeFile(join(directory, "deleted.txt"), "delete this\n");
  await git("add", ".");
  await git("-c", "core.hooksPath=/dev/null", "commit", "-m", "fixture");
  const head = await git("rev-parse", "HEAD");
  await git("checkout", "--detach", head);
  await rename(join(directory, "original.txt"), join(directory, "renamed\tfile.txt"));
  await unlink(join(directory, "deleted.txt"));
  await writeFile(join(directory, "binary.dat"), Buffer.from([0, 1, 2, 3, 255]));
  await git("add", "-A");
  const tree = await git("write-tree");
  const preview = await readGitCommitPreview(directory);
  expect(preview.branch).toBeNull();
  expect(preview.head).toBe(head);
  expect(preview.stagedFiles).toContain("renamed\tfile.txt");
  expect(preview.stagedFiles).toContain("deleted.txt");
  expect(preview.stagedPatch).toContain("GIT binary patch");
  expect(preview.hasUnstagedChanges).toBe(false);
  expect(preview.hasUntrackedFiles).toBe(false);
  expect(await git("write-tree")).toBe(tree);
  await git("reset", "--mixed", head);
  const empty = await readGitCommitPreview(directory);
  expect(empty.stagedFiles).toEqual([]);
  expect(empty.stagedPatch).toBe("");
  expect(empty.fingerprint).not.toBe(preview.fingerprint);
});

it("rejects a conflicted index without resolving or modifying it", async () => {
  const directory = await mkdtemp(join(tmpdir(), "ui-kit-commit-preview-conflict-"));
  const exec = promisify(execFile);
  const git = async (...args: string[]) => (await exec("git", args, { cwd: directory })).stdout.trim();
  await git("init", "-b", "main");
  await git("config", "user.name", "Preview Test");
  await git("config", "user.email", "preview@example.invalid");
  await writeFile(join(directory, "conflict.txt"), "base\n");
  await git("add", ".");
  await git("-c", "core.hooksPath=/dev/null", "commit", "-m", "base");
  await git("checkout", "-b", "other");
  await writeFile(join(directory, "conflict.txt"), "other\n");
  await git("-c", "core.hooksPath=/dev/null", "commit", "-am", "other");
  await git("checkout", "main");
  await writeFile(join(directory, "conflict.txt"), "main\n");
  await git("-c", "core.hooksPath=/dev/null", "commit", "-am", "main");
  await expect(git("merge", "other")).rejects.toThrow();
  const before = await git("ls-files", "--unmerged");
  const content = await readFile(join(directory, "conflict.txt"), "utf8");
  await expect(readGitCommitPreview(directory)).rejects.toThrow("Resolve merge conflicts");
  expect(await git("ls-files", "--unmerged")).toBe(before);
  expect(await readFile(join(directory, "conflict.txt"), "utf8")).toBe(content);
});

it("requires a fresh preview, honors failing hooks, and commits only staged content", async () => {
  const directory = await mkdtemp(join(tmpdir(), "ui-kit-confirm-commit-"));
  const exec = promisify(execFile);
  const git = async (...args: string[]) => (await exec("git", args, { cwd: directory })).stdout.trim();
  await git("init", "-b", "main");
  await git("config", "user.name", "Commit Test");
  await git("config", "user.email", "commit@example.invalid");
  await git("config", "commit.gpgsign", "false");
  await git("config", "core.hooksPath", ".git/hooks");
  await writeFile(join(directory, "file.txt"), "first staged\n");
  await git("add", ".");
  const stale = await readGitCommitPreview(directory);
  await writeFile(join(directory, "file.txt"), "reviewed staged\n");
  await git("add", ".");
  await expect(commitGitPreview(directory, stale.fingerprint, "test: commit")).rejects.toThrow("Git changed");
  await expect(git("rev-parse", "--verify", "HEAD")).rejects.toThrow();
  const preview = await readGitCommitPreview(directory);
  await writeFile(join(directory, "file.txt"), "unapproved unstaged\n");
  await writeFile(join(directory, "untracked.txt"), "unapproved untracked\n");
  const hook = join(directory, ".git/hooks/pre-commit");
  await writeFile(hook, "#!/bin/sh\nexit 1\n");
  await chmod(hook, 0o755);
  await expect(commitGitPreview(directory, preview.fingerprint, "test: commit")).rejects.toThrow();
  await expect(git("rev-parse", "--verify", "HEAD")).rejects.toThrow();
  expect((await readGitCommitPreview(directory)).fingerprint).toBe(preview.fingerprint);
  await unlink(hook);
  const result = await commitGitPreview(directory, preview.fingerprint, "test: reviewed content");
  expect(result.head).toBe(await git("rev-parse", "HEAD"));
  expect(await git("show", "HEAD:file.txt")).toBe("reviewed staged");
  expect(await git("ls-tree", "--name-only", "HEAD")).toBe("file.txt");
  expect(await readFile(join(directory, "file.txt"), "utf8")).toBe("unapproved unstaged\n");
  expect(await readFile(join(directory, "untracked.txt"), "utf8")).toBe("unapproved untracked\n");
  const empty = await readGitCommitPreview(directory);
  await expect(commitGitPreview(directory, empty.fingerprint, "test: empty")).rejects.toThrow("no staged changes");
});
